### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Comment by little-arhat** [comment]
@outplay-services try

**Comment by outplay-services** [comment]
:hourglass: Trying commit d4d31d2 with merge a132b48...

**Comment by outplay-services** [comment]
:broken_heart: Test failed: 
`Could not find or parse Dockerfile: Missing Dockerfile in build package` - [quay](https://quay.io/repository/outplay/homu/build?current=de60c964-a4bc-4a37-8d0f-aee114e65a6f)

**Comment by little-arhat** [comment]
@outplay-services try

**Comment by little-arhat** [comment]
@outplay-services retry

**Comment by outplay-services** [comment]
:hourglass: Trying commit d4d31d2 with merge 4e88f61...

**Comment by outplay-services** [comment]
:broken_heart: Test failed: 
`Could not find or parse Dockerfile: Missing Dockerfile in build package` - [quay](https://quay.io/repository/outplay/homu/build?current=266f7ecd-eadd-47f3-bdb8-9e6cde2c3a3b)

**Comment by little-arhat** [comment]
@outplay-services retry

**Comment by regadas** [comment]
@outplay-services retry

**Comment by regadas** [comment]
@outplay-services clean

**Comment by regadas** [comment]
@outplay-services try

**Comment by outplay-services** [comment]
:hourglass: Trying commit ec8d7ae with merge 493066a...

**Comment by outplay-services** [comment]
:broken_heart: Test failed: 
`Could not find or parse Dockerfile: Missing Dockerfile in build package` - [quay](https://quay.io/repository/outplay/homu/build?current=0db6814e-f0fa-474e-86ca-c4eac5da7dc9)

**Comment by outplay-services** [comment]
:sunny: Test successful - [quay](https://quay.io/repository/outplay/homu/build?current=474f4509-7c79-4ddd-831e-fb784b0a4fdd)

**Comment by regadas** [comment]
@outplay-services try

**Comment by regadas** [comment]
@outplay-services clean

**Comment by regadas** [comment]
@outplay-services try

**Comment by regadas** [comment]
@outplay-services clean

**Comment by regadas** [comment]
@outplay-services try

**Comment by regadas** [comment]
@outplay-services r+

**Comment by outplay-services** [comment]
:pushpin: Commit ec8d7ae has been approved by `regadas`

**Comment by outplay-services** [comment]
:hourglass: Testing commit ec8d7ae with merge 2bb013f...

**Comment by outplay-services** [comment]
:broken_heart: Test failed: 
`Could not find or parse Dockerfile: Missing Dockerfile in build package` - [quay](https://quay.io/repository/outplay/homu/build?current=eebb40aa-a672-48f4-a6d3-99079d475140)

**Pull request merged**
