### PR TITLE
Update dockerignore

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Comment by regadas** [comment]
@outplay-services try

**Comment by outplay-services** [comment]
:hourglass: Trying commit 9b29fc5 with merge eee9e73...

**Comment by outplay-services** [comment]
:sunny: Test successful - [quay](https://quay.io/repository/outplay/homu/build?current=1db6e1eb-318c-47ce-b84c-f38cd73d9de4)

**Comment by regadas** [comment]
@outplay-services retry

**Comment by regadas** [comment]
@outplay-services clean

**Comment by regadas** [comment]
@outplay-services try

**Comment by outplay-services** [comment]
:hourglass: Trying commit 2effd7e with merge 6167550...

**Comment by outplay-services** [comment]
:sunny: Test successful - [quay](https://quay.io/repository/outplay/homu/build?current=7e8c8240-d0cc-4f3a-9817-ece0dc0271db)

**Comment by regadas** [comment]
@outplay-services try

**Comment by regadas** [comment]
@outplay-services retry

**Comment by outplay-services** [comment]
:hourglass: Trying commit 2effd7e with merge 23181d1...

**Comment by outplay-services** [comment]
:sunny: Test successful - [quay](https://quay.io/repository/outplay/homu/build?current=932eb0f6-2e67-43e6-a800-d34f83a7b366)

**Comment by regadas** [comment]
this was just quay+homu test

**Pull request closed without merging**
